#!/usr/bin/env sh
set -euxo pipefail

echo "TODO"

# pnpm install
# pnpm run --parallel clean
# pnpm run --recursive --filter './packages/*' build
# pnpm run --parallel dev

# TODO start these in two panes
# pnpm run services:dev
# pnpm run packages:dev
